# Generated by Django 3.1.1 on 2021-02-28 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locationandfeedback', '0003_auto_20210227_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='group',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='student',
        ),
    ]
