# Generated by Django 3.1.1 on 2020-11-14 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0008_image_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
