# Generated by Django 3.1.1 on 2020-11-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0009_auto_20201114_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='image1',
            field=models.ImageField(default=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.ImageField(default=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image3',
            field=models.ImageField(default=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image4',
            field=models.ImageField(default=True, upload_to='images/'),
        ),
    ]
