# Generated by Django 3.1.1 on 2020-11-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0010_auto_20201114_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='breadth',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='length',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='url_location',
            field=models.URLField(null=True),
        ),
    ]
