# Generated by Django 3.1.1 on 2021-02-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0014_auto_20210210_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='payment_method',
            field=models.CharField(choices=[('Khalti', 'Khalti'), ('E-Sewa', 'E-Sewa')], default='Khalti', max_length=20),
        ),
    ]
