# Generated by Django 3.0.1 on 2021-02-26 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0016_auto_20210226_1359'),
        ('Post', '0015_auto_20210211_1659'),
    ]

    operations = [
    ]
