# Generated by Django 3.1.1 on 2021-02-26 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0017_merge_20210226_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='payment_method',
        ),
    ]
