# Generated by Django 3.1.1 on 2021-02-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0019_auto_20210226_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='district',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='province',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
