# Generated by Django 3.1.1 on 2021-02-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0020_auto_20210227_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
