# Generated by Django 3.1.1 on 2021-03-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0024_auto_20210302_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='payment_verification_slip',
            field=models.ImageField(default=True, upload_to='images/'),
        ),
    ]
