# Generated by Django 3.1.1 on 2021-03-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0027_auto_20210303_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='backsideview',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='frontview',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='leftsideview',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='payment_verification_slip',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rightsideview',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
